namespace Anno1404Calculator.Models;

using System;
using System.Collections.Generic;
using System.Text;

public enum ProductionBuildingEnum
{
    // Intermediate buildings
    Sugarcaneplantation,
    Sugarmill,
    Silkplantation,
    Rosenursery,
    Hempplantation,
    Goldsmelter,
    Goldmine,
    Coppersmelter,
    Coppermine,
    Coffeeplantation,
    Candlemakersworkshop,
    Apiary,
    Almondplantation,
    Cropfarm,
    Mill,
    Monasterygarden,
    Coalmine,
    Saltmine,
    Saltworks,
    Pigfarm,
    Papermill,
    Indigofarm,
    Lumberjackshut,
    Cattlefarm,
    Trapperslodge,
    Vineyard,
    Barrelcooperage,
    Claypit,
    Quartzquarry,
    Ironmine,
    Ironsmelter,
    Pearlfishershut,
    // final buildings
    Fishermanshut,
    Ciderfarm,
    Weavershut,
    Bakery,
    Monasterybrewery,
    Tannery,
    Printinghouse,
    Butchersshop,
    Furriersworkshop,
    Winepress,
    Redsmithsworkshop,
    Opticiansworkshop,
    Confectionersworkshop,
    Perfumery,
    Pearlworkshop,
    Roastinghouse,
    Carpetworkshop,
    Dateplantation,
    Goatfarm,
    Silkweavingmill,
    Spicefarm,
    Charcoalburnershut,
    Forestglassworks,
    // Misc buildings (tools, stone, mosaic, weapons, cannons, ropes, war machines, glas)
    Toolmakersworkshop,
    Stonemasonshut,
    Ropeyard,
    Weaponsmithy,
    Mosaicworkshop,
    Warmachinesworkshop,
    Cannonfoundry,
    Glasssmelter,
}

public static class Anno1404IntermediateBuildingExtensions
{
    public static uint GetBuildingId(this ProductionBuildingEnum ib) =>
        ib switch
        {
            ProductionBuildingEnum.Sugarcaneplantation => 0x7577,
            ProductionBuildingEnum.Sugarmill => 0x7d1e,
            ProductionBuildingEnum.Silkplantation => 0x7578,
            ProductionBuildingEnum.Rosenursery => 0x757a,
            ProductionBuildingEnum.Hempplantation => 0x7544,
            ProductionBuildingEnum.Goldsmelter => throw new NotImplementedException(),
            ProductionBuildingEnum.Goldmine => throw new NotImplementedException(),
            ProductionBuildingEnum.Coppersmelter => 0x7d23,
            ProductionBuildingEnum.Coppermine => 0x7b13,
            ProductionBuildingEnum.Coffeeplantation => 0x7574,
            ProductionBuildingEnum.Candlemakersworkshop => 0x7d25,
            ProductionBuildingEnum.Apiary => 0x7579,
            ProductionBuildingEnum.Almondplantation => 0x756d,
            ProductionBuildingEnum.Cropfarm => 0x756e,
            ProductionBuildingEnum.Mill => 0x7d0e,
            ProductionBuildingEnum.Monasterygarden => 0x756f,
            ProductionBuildingEnum.Coalmine => 0x7b12,
            ProductionBuildingEnum.Saltmine => 0x7b10,
            ProductionBuildingEnum.Saltworks => 0x7d17,
            ProductionBuildingEnum.Pigfarm => 0x7572,
            ProductionBuildingEnum.Papermill => 0x757d,
            ProductionBuildingEnum.Indigofarm => 0x757b,
            ProductionBuildingEnum.Lumberjackshut => 0x7558,
            ProductionBuildingEnum.Cattlefarm => 0x7570,
            ProductionBuildingEnum.Trapperslodge => 0x7575,
            ProductionBuildingEnum.Vineyard => 0x7573,
            ProductionBuildingEnum.Barrelcooperage => 0x7d19,
            ProductionBuildingEnum.Quartzquarry => 0x7b0d,
            ProductionBuildingEnum.Ironmine => 0x7b0f,
            ProductionBuildingEnum.Ironsmelter => 0x7d14,
            ProductionBuildingEnum.Pearlfishershut => 0x757c,
            ProductionBuildingEnum.Confectionersworkshop => 0x7d1f,
            ProductionBuildingEnum.Perfumery => 0x7d27,
            ProductionBuildingEnum.Pearlworkshop => 0x7d2a,
            ProductionBuildingEnum.Roastinghouse => 0x7d1b,
            ProductionBuildingEnum.Carpetworkshop => 0x7d28,
            ProductionBuildingEnum.Dateplantation => 0x757e,
            ProductionBuildingEnum.Goatfarm => 0x756c,
            ProductionBuildingEnum.Toolmakersworkshop => 0x7d0b,
            ProductionBuildingEnum.Stonemasonshut => 0x7b0e,
            ProductionBuildingEnum.Ropeyard => 0x7d15,
            ProductionBuildingEnum.Weaponsmithy => 0x7d16,
            ProductionBuildingEnum.Mosaicworkshop => 0x7d0d,
            ProductionBuildingEnum.Fishermanshut => 0x7562,
            ProductionBuildingEnum.Ciderfarm => 0x753a,
            ProductionBuildingEnum.Weavershut => 0x7d00,
            ProductionBuildingEnum.Bakery => 0x7d0f,
            ProductionBuildingEnum.Monasterybrewery => 0x7d10,
            ProductionBuildingEnum.Tannery => 0x7d11,
            ProductionBuildingEnum.Printinghouse => 0x7d2b,
            ProductionBuildingEnum.Butchersshop => 0x7d18,
            ProductionBuildingEnum.Furriersworkshop => 0x7d1c,
            ProductionBuildingEnum.Winepress => 0x7d1a,
            ProductionBuildingEnum.Redsmithsworkshop => 0x7d26,
            ProductionBuildingEnum.Opticiansworkshop => 0x7d24,
            ProductionBuildingEnum.Warmachinesworkshop => 0x7d1d,
            ProductionBuildingEnum.Claypit => 0x7918,
            ProductionBuildingEnum.Silkweavingmill => throw new NotImplementedException(),
            ProductionBuildingEnum.Cannonfoundry => 0x7d21,
            ProductionBuildingEnum.Spicefarm => 0x7530,
            ProductionBuildingEnum.Charcoalburnershut => 0x7571,
            ProductionBuildingEnum.Forestglassworks => 0x7d22,
            ProductionBuildingEnum.Glasssmelter => 0x7d2c,
            _ => throw new NotImplementedException(),
        };

    public static double GetProductionPerMinuteFactor(this ProductionBuildingEnum pt) =>
        pt switch
        {
            ProductionBuildingEnum.Monasterybrewery => 1.5,
            ProductionBuildingEnum.Printinghouse => 3.0,
            ProductionBuildingEnum.Bakery => 4.0,
            ProductionBuildingEnum.Silkweavingmill => 3.0,
            ProductionBuildingEnum.Redsmithsworkshop => 2.0,
            ProductionBuildingEnum.Carpetworkshop => 1.5,
            ProductionBuildingEnum.Ciderfarm => 1.5,
            ProductionBuildingEnum.Roastinghouse => 1.0,
            ProductionBuildingEnum.Dateplantation => 3.0,
            ProductionBuildingEnum.Fishermanshut => 2.0,
            ProductionBuildingEnum.Furriersworkshop => 2.5,
            ProductionBuildingEnum.Opticiansworkshop => 2.0,
            ProductionBuildingEnum.Tannery => 4.0,
            ProductionBuildingEnum.Weavershut => 2.0,
            ProductionBuildingEnum.Confectionersworkshop => 4.0,
            ProductionBuildingEnum.Butchersshop => 2.5,
            ProductionBuildingEnum.Goatfarm => 1.5,
            ProductionBuildingEnum.Pearlworkshop => 1.0,
            ProductionBuildingEnum.Perfumery => 1.0,
            ProductionBuildingEnum.Spicefarm => 2.0,
            ProductionBuildingEnum.Winepress => 2.0,
            ProductionBuildingEnum.Sugarcaneplantation => 2.0,
            ProductionBuildingEnum.Sugarmill => 4.0,
            ProductionBuildingEnum.Silkplantation => 1.5,
            ProductionBuildingEnum.Rosenursery => 0.5,
            ProductionBuildingEnum.Hempplantation => 1.0,
            ProductionBuildingEnum.Goldsmelter => 1.5,
            ProductionBuildingEnum.Goldmine => 1.33,
            ProductionBuildingEnum.Coppersmelter => 1.333333,
            ProductionBuildingEnum.Coppermine => 1.333333,
            ProductionBuildingEnum.Coffeeplantation => 1.0,
            ProductionBuildingEnum.Candlemakersworkshop => 1.333333,
            ProductionBuildingEnum.Apiary => 0.67,
            ProductionBuildingEnum.Almondplantation => 2.0,
            ProductionBuildingEnum.Cropfarm => 2.0,
            ProductionBuildingEnum.Mill => 4.0,
            ProductionBuildingEnum.Monasterygarden => 1.5,
            ProductionBuildingEnum.Coalmine => 4.0,
            ProductionBuildingEnum.Saltmine => 4.0,
            ProductionBuildingEnum.Saltworks => 4.0,
            ProductionBuildingEnum.Pigfarm => 2.0,
            ProductionBuildingEnum.Papermill => 3.0,
            ProductionBuildingEnum.Indigofarm => 1.5,
            ProductionBuildingEnum.Lumberjackshut => 1.5,
            ProductionBuildingEnum.Cattlefarm => 1.25,
            ProductionBuildingEnum.Trapperslodge => 2.5,
            ProductionBuildingEnum.Vineyard => 0.666666,
            ProductionBuildingEnum.Barrelcooperage => 2.0,
            ProductionBuildingEnum.Claypit => 1.2,
            ProductionBuildingEnum.Quartzquarry => 1.33,
            ProductionBuildingEnum.Ironmine => 2.0,
            ProductionBuildingEnum.Ironsmelter => 2.0,
            ProductionBuildingEnum.Pearlfishershut => 1.0,
            ProductionBuildingEnum.Charcoalburnershut => 2.0,
            ProductionBuildingEnum.Forestglassworks => 2.0,
            ProductionBuildingEnum.Toolmakersworkshop => 2.0,
            ProductionBuildingEnum.Stonemasonshut => 2.0,
            ProductionBuildingEnum.Ropeyard => 2.0,
            ProductionBuildingEnum.Weaponsmithy => 2.0,
            ProductionBuildingEnum.Mosaicworkshop => 2.4,
            ProductionBuildingEnum.Warmachinesworkshop => 1.5,
            ProductionBuildingEnum.Cannonfoundry => 1.0,
            ProductionBuildingEnum.Glasssmelter => 2.0,
            _ => throw new NotImplementedException()
        };

    public static double GetProductionPerMinute(this ProductionBuildingEnum pb, AnnoPlayerStatus status, uint totalBuildings, uint buildings00, uint buildings25, uint buildings50, uint buildings75)
    {
        var production = (buildings00 + buildings25 * 1.25 + buildings50 * 1.5 + buildings75 * 1.75) * pb.GetProductionPerMinuteFactor();
        if (totalBuildings > (buildings00 + buildings25 + buildings50 + buildings75))
        {
            production += (totalBuildings - (buildings00 + buildings25 + buildings50 + buildings75)) * pb.GetProductionPerMinuteFactor();
        }
        if (pb == ProductionBuildingEnum.Coalmine)
        {
            production += status.Charcoalburnershuts * ProductionBuildingEnum.Charcoalburnershut.GetProductionPerMinuteFactor();
        }
        return production;
    }

    /// <summary>
    /// Calculate the consumption in tons/minute.
    /// </summary>
    /// <param name="pb"></param>
    /// <param name="status"></param>
    /// <returns></returns>
    /// <exception cref="NotImplementedException"></exception>
    public static double GetConsumptionPerMinute(this ProductionBuildingEnum pb, AnnoPlayerStatus status) =>
        pb switch
        {
            ProductionBuildingEnum.Sugarcaneplantation => (status.Sugarmills * 2.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Sugarmill => (status.Confectionersworkshops * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Silkplantation => (status.Carpetworkshops * 1.0 + status.Silkweavingmills * 2.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Rosenursery => (status.Perfumeries * 3.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Hempplantation => (status.Weavershuts * 2 + status.Ropeyards * 1 + status.Candlemakersworkshops * 1) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Goldsmelter => (status.Silkweavingmills * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Goldmine => (status.Goldmines * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Coppersmelter => (status.Redsmithsworkshops * 0.75 + status.Opticiansworkshops * 0.75) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Coppermine => (status.Coppersmelters * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Coffeeplantation => (status.Roastinghouses * 2) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Candlemakersworkshop => (status.Redsmithsworkshops * 0.666666) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Apiary => (status.Candlemakersworkshops * 0.5) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Almondplantation => (status.Confectionersworkshops * 2.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Cropfarm => (status.Mills * 2 + status.Monasterybreweries * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Mill => (status.Bakeries * 1) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Monasterygarden => (status.Monasterybreweries * 1) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Coalmine => (status.Coppersmelters * 0.333333 + status.Ironsmelters * 0.5 + status.Saltworks * 0.5 + status.Goldsmelters * 0.375) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Saltmine => (status.Saltworks * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Saltworks => (status.Tanneries * 0.5 + status.Butchersshops * 0.5 + status.Furriersworkshops * 0.333333) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Pigfarm => (status.Tanneries * 2) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Papermill => (status.Printinghouses * 0.5) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Indigofarm => (status.Carpetworkshops * 1.0 + status.Printinghouses * 2) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Lumberjackshut => (status.Barrelcooperages * 1.0 + status.Warmachinesworkshops * 0.5) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Cattlefarm => (status.Butchersshops * 2.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Trapperslodge => (status.Furriersworkshops * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Vineyard => (status.Winepresses * 3.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Barrelcooperage => (status.Winepresses * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Claypit => (status.Mosaicworkshops * 2.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Quartzquarry => (status.Mosaicworkshops * 0.9 + status.Glasssmelters * 0.375) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Ironmine => (status.Ironsmelters * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Ironsmelter => (status.Barrelcooperages * 0.5 + status.Toolmakersworkshops * 0.5 + status.Cannonfoundries * 0.75 + status.Weaponsmithies * 1.0) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Pearlfishershut => (status.Pearlworkshops * 1) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Fishermanshut => status.Beggars * 0.007 + status.Peasants * 0.01 + status.Citizens * 0.004 + status.Patricians * 0.0022 + status.Noblemen * 0.0016,
            ProductionBuildingEnum.Ciderfarm => status.Beggars * 0.003 + status.Peasants * 0.0044 + status.Citizens * 0.0044 + status.Patricians * 0.0023 + status.Noblemen * 0.0013,
            ProductionBuildingEnum.Weavershut => status.Citizens * 0.0042 + status.Patricians * 0.0019 + status.Noblemen * 0.0008,
            ProductionBuildingEnum.Bakery => status.Patricians * 0.0055 + status.Noblemen * 0.0039,
            ProductionBuildingEnum.Monasterybrewery => status.Patricians * 0.0024 + status.Noblemen * 0.0014,
            ProductionBuildingEnum.Tannery => status.Patricians * 0.0028 + status.Noblemen * 0.0016,
            ProductionBuildingEnum.Printinghouse => status.Patricians * 0.0016 + status.Noblemen * 0.0009,
            ProductionBuildingEnum.Butchersshop => status.Noblemen * 0.0022,
            ProductionBuildingEnum.Furriersworkshop => status.Noblemen * 0.0016,
            ProductionBuildingEnum.Winepress => status.Noblemen * 0.002,
            ProductionBuildingEnum.Redsmithsworkshop => status.Patricians * 0.0008 + status.Noblemen * 0.0006,
            ProductionBuildingEnum.Opticiansworkshop => status.Noblemen * 0.00117,
            ProductionBuildingEnum.Confectionersworkshop => status.Envoys * 0.00163,
            ProductionBuildingEnum.Perfumery => status.Envoys * 0.0008,
            ProductionBuildingEnum.Pearlworkshop => status.Envoys * 0.00133,
            ProductionBuildingEnum.Roastinghouse => status.Envoys * 0.001,
            ProductionBuildingEnum.Carpetworkshop => status.Nomads * 0.00165 + status.Envoys * 0.001,
            ProductionBuildingEnum.Dateplantation => status.Nomads * 0.00666 + status.Envoys * 0.005,
            ProductionBuildingEnum.Goatfarm => status.Nomads * 0.00344 + status.Envoys * 0.00225,
            ProductionBuildingEnum.Silkweavingmill => status.Noblemen * 0.00142,
            ProductionBuildingEnum.Spicefarm => status.Citizens * 0.0044 + status.Patricians * 0.0022 + status.Noblemen * 0.0016,
            ProductionBuildingEnum.Charcoalburnershut => throw new NotImplementedException(),
            ProductionBuildingEnum.Forestglassworks => (status.Glasssmelters * 0.5) * pb.GetProductionPerMinuteFactor(),
            ProductionBuildingEnum.Toolmakersworkshop => 0,
            ProductionBuildingEnum.Stonemasonshut => 0,
            ProductionBuildingEnum.Ropeyard => 0,
            ProductionBuildingEnum.Weaponsmithy => 0,
            ProductionBuildingEnum.Mosaicworkshop => 0,
            ProductionBuildingEnum.Warmachinesworkshop => 0,
            ProductionBuildingEnum.Cannonfoundry => 0,
            ProductionBuildingEnum.Glasssmelter => 0,
            _ => throw new NotImplementedException(),
        };
}

// TODO replace this sometime
public enum Anno1404ProductType
{
    Beer,
    Books,
    Bread,
    BrocadeRobes,
    Candlestick,
    Carpets,
    Cider,
    Coffee,
    Dates,
    Fish,
    FurCoats,
    Glasses,
    LeatherJerkins,
    LinenGarments,
    Marzipan,
    Meat,
    Milk,
    PearlNecklaces,
    Perfume,
    Spices,
    Wine
}