namespace Anno1404Calculator.Models;

using Anno1404Calculator.Models.ProductionBuildings;
using System;
using System.Collections.Generic;
using System.Text;

public enum ProductionBuildingEnum
{
    // Intermediate buildings
    Sugarcaneplantation,
    Sugarmill,
    Silkplantation,
    Rosenursery,
    Hempplantation,
    Goldsmelter,
    Goldmine,
    Coppersmelter,
    Coppermine,
    Coffeeplantation,
    Candlemakersworkshop,
    Apiary,
    Almondplantation,
    Cropfarm,
    Mill,
    Monasterygarden,
    Coalmine,
    Saltmine,
    Saltworks,
    Pigfarm,
    Papermill,
    Indigofarm,
    Lumberjackshut,
    Cattlefarm,
    Trapperslodge,
    Vineyard,
    Barrelcooperage,
    Claypit,
    Quartzquarry,
    Ironmine,
    Ironsmelter,
    Pearlfishershut,
    // final buildings
    Fishermanshut,
    Ciderfarm,
    Weavershut,
    Bakery,
    Monasterybrewery,
    Tannery,
    Printinghouse,
    Butchersshop,
    Furriersworkshop,
    Winepress,
    Redsmithsworkshop,
    Opticiansworkshop,
    Confectionersworkshop,
    Perfumery,
    Pearlworkshop,
    Roastinghouse,
    Carpetworkshop,
    Dateplantation,
    Goatfarm,
    Silkweavingmill,
    Spicefarm,
    Charcoalburnershut,
    Forestglassworks,
    // Misc buildings (tools, stone, mosaic, weapons, cannons, ropes, war machines, glas)
    Toolmakersworkshop,
    Stonemasonshut,
    Ropeyard,
    Weaponsmithy,
    Mosaicworkshop,
    Warmachinesworkshop,
    Cannonfoundry,
    Glasssmelter,
}

public static class Anno1404IntermediateBuildingExtensions
{
    public static Type GetProductionBuildingType(this ProductionBuildingEnum e) =>
        e switch
        {
            ProductionBuildingEnum.Sugarcaneplantation => throw new NotImplementedException(),
            ProductionBuildingEnum.Sugarmill => throw new NotImplementedException(),
            ProductionBuildingEnum.Silkplantation => throw new NotImplementedException(),
            ProductionBuildingEnum.Rosenursery => throw new NotImplementedException(),
            ProductionBuildingEnum.Hempplantation => typeof(Hempplantation),
            ProductionBuildingEnum.Goldsmelter => throw new NotImplementedException(),
            ProductionBuildingEnum.Goldmine => throw new NotImplementedException(),
            ProductionBuildingEnum.Coppersmelter => throw new NotImplementedException(),
            ProductionBuildingEnum.Coppermine => throw new NotImplementedException(),
            ProductionBuildingEnum.Coffeeplantation => throw new NotImplementedException(),
            ProductionBuildingEnum.Candlemakersworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Apiary => throw new NotImplementedException(),
            ProductionBuildingEnum.Almondplantation => throw new NotImplementedException(),
            ProductionBuildingEnum.Cropfarm => throw new NotImplementedException(),
            ProductionBuildingEnum.Mill => throw new NotImplementedException(),
            ProductionBuildingEnum.Monasterygarden => throw new NotImplementedException(),
            ProductionBuildingEnum.Coalmine => throw new NotImplementedException(),
            ProductionBuildingEnum.Saltmine => throw new NotImplementedException(),
            ProductionBuildingEnum.Saltworks => throw new NotImplementedException(),
            ProductionBuildingEnum.Pigfarm => throw new NotImplementedException(),
            ProductionBuildingEnum.Papermill => throw new NotImplementedException(),
            ProductionBuildingEnum.Indigofarm => throw new NotImplementedException(),
            ProductionBuildingEnum.Lumberjackshut => throw new NotImplementedException(),
            ProductionBuildingEnum.Cattlefarm => throw new NotImplementedException(),
            ProductionBuildingEnum.Trapperslodge => throw new NotImplementedException(),
            ProductionBuildingEnum.Vineyard => throw new NotImplementedException(),
            ProductionBuildingEnum.Barrelcooperage => throw new NotImplementedException(),
            ProductionBuildingEnum.Claypit => throw new NotImplementedException(),
            ProductionBuildingEnum.Quartzquarry => throw new NotImplementedException(),
            ProductionBuildingEnum.Ironmine => throw new NotImplementedException(),
            ProductionBuildingEnum.Ironsmelter => throw new NotImplementedException(),
            ProductionBuildingEnum.Pearlfishershut => throw new NotImplementedException(),
            ProductionBuildingEnum.Fishermanshut => throw new NotImplementedException(),
            ProductionBuildingEnum.Ciderfarm => throw new NotImplementedException(),
            ProductionBuildingEnum.Weavershut => throw new NotImplementedException(),
            ProductionBuildingEnum.Bakery => throw new NotImplementedException(),
            ProductionBuildingEnum.Monasterybrewery => throw new NotImplementedException(),
            ProductionBuildingEnum.Tannery => throw new NotImplementedException(),
            ProductionBuildingEnum.Printinghouse => throw new NotImplementedException(),
            ProductionBuildingEnum.Butchersshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Furriersworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Winepress => throw new NotImplementedException(),
            ProductionBuildingEnum.Redsmithsworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Opticiansworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Confectionersworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Perfumery => throw new NotImplementedException(),
            ProductionBuildingEnum.Pearlworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Roastinghouse => throw new NotImplementedException(),
            ProductionBuildingEnum.Carpetworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Dateplantation => throw new NotImplementedException(),
            ProductionBuildingEnum.Goatfarm => throw new NotImplementedException(),
            ProductionBuildingEnum.Silkweavingmill => throw new NotImplementedException(),
            ProductionBuildingEnum.Spicefarm => throw new NotImplementedException(),
            ProductionBuildingEnum.Charcoalburnershut => throw new NotImplementedException(),
            ProductionBuildingEnum.Forestglassworks => throw new NotImplementedException(),
            ProductionBuildingEnum.Toolmakersworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Stonemasonshut => throw new NotImplementedException(),
            ProductionBuildingEnum.Ropeyard => throw new NotImplementedException(),
            ProductionBuildingEnum.Weaponsmithy => throw new NotImplementedException(),
            ProductionBuildingEnum.Mosaicworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Warmachinesworkshop => throw new NotImplementedException(),
            ProductionBuildingEnum.Cannonfoundry => throw new NotImplementedException(),
            ProductionBuildingEnum.Glasssmelter => throw new NotImplementedException(),
            _ => throw new NotImplementedException(),
        };

    public static uint GetBuildingId(this ProductionBuildingEnum ib) =>
        ib switch
        {
            ProductionBuildingEnum.Sugarcaneplantation => 0x7577,
            ProductionBuildingEnum.Sugarmill => 0x7d1e,
            ProductionBuildingEnum.Silkplantation => 0x7578,
            ProductionBuildingEnum.Rosenursery => 0x757a,
            ProductionBuildingEnum.Hempplantation => 0x7544,
            ProductionBuildingEnum.Goldsmelter => throw new NotImplementedException(),
            ProductionBuildingEnum.Goldmine => throw new NotImplementedException(),
            ProductionBuildingEnum.Coppersmelter => 0x7d23,
            ProductionBuildingEnum.Coppermine => 0x7b13,
            ProductionBuildingEnum.Coffeeplantation => 0x7574,
            ProductionBuildingEnum.Candlemakersworkshop => 0x7d25,
            ProductionBuildingEnum.Apiary => 0x7579,
            ProductionBuildingEnum.Almondplantation => 0x756d,
            ProductionBuildingEnum.Cropfarm => 0x756e,
            ProductionBuildingEnum.Mill => 0x7d0e,
            ProductionBuildingEnum.Monasterygarden => 0x756f,
            ProductionBuildingEnum.Coalmine => 0x7b12,
            ProductionBuildingEnum.Saltmine => 0x7b10,
            ProductionBuildingEnum.Saltworks => 0x7d17,
            ProductionBuildingEnum.Pigfarm => 0x7572,
            ProductionBuildingEnum.Papermill => 0x757d,
            ProductionBuildingEnum.Indigofarm => 0x757b,
            ProductionBuildingEnum.Lumberjackshut => 0x7558,
            ProductionBuildingEnum.Cattlefarm => 0x7570,
            ProductionBuildingEnum.Trapperslodge => 0x7575,
            ProductionBuildingEnum.Vineyard => 0x7573,
            ProductionBuildingEnum.Barrelcooperage => 0x7d19,
            ProductionBuildingEnum.Quartzquarry => 0x7b0d,
            ProductionBuildingEnum.Ironmine => 0x7b0f,
            ProductionBuildingEnum.Ironsmelter => 0x7d14,
            ProductionBuildingEnum.Pearlfishershut => 0x757c,
            ProductionBuildingEnum.Confectionersworkshop => 0x7d1f,
            ProductionBuildingEnum.Perfumery => 0x7d27,
            ProductionBuildingEnum.Pearlworkshop => 0x7d2a,
            ProductionBuildingEnum.Roastinghouse => 0x7d1b,
            ProductionBuildingEnum.Carpetworkshop => 0x7d28,
            ProductionBuildingEnum.Dateplantation => 0x757e,
            ProductionBuildingEnum.Goatfarm => 0x756c,
            ProductionBuildingEnum.Toolmakersworkshop => 0x7d0b,
            ProductionBuildingEnum.Stonemasonshut => 0x7b0e,
            ProductionBuildingEnum.Ropeyard => 0x7d15,
            ProductionBuildingEnum.Weaponsmithy => 0x7d16,
            ProductionBuildingEnum.Mosaicworkshop => 0x7d0d,
            ProductionBuildingEnum.Fishermanshut => 0x7562,
            ProductionBuildingEnum.Ciderfarm => 0x753a,
            ProductionBuildingEnum.Weavershut => 0x7d00,
            ProductionBuildingEnum.Bakery => 0x7d0f,
            ProductionBuildingEnum.Monasterybrewery => 0x7d10,
            ProductionBuildingEnum.Tannery => 0x7d11,
            ProductionBuildingEnum.Printinghouse => 0x7d2b,
            ProductionBuildingEnum.Butchersshop => 0x7d18,
            ProductionBuildingEnum.Furriersworkshop => 0x7d1c,
            ProductionBuildingEnum.Winepress => 0x7d1a,
            ProductionBuildingEnum.Redsmithsworkshop => 0x7d26,
            ProductionBuildingEnum.Opticiansworkshop => 0x7d24,
            ProductionBuildingEnum.Warmachinesworkshop => 0x7d1d,
            ProductionBuildingEnum.Claypit => 0x7918,
            ProductionBuildingEnum.Silkweavingmill => throw new NotImplementedException(),
            ProductionBuildingEnum.Cannonfoundry => 0x7d21,
            ProductionBuildingEnum.Spicefarm => 0x7530,
            ProductionBuildingEnum.Charcoalburnershut => throw new NotImplementedException(),
            _ => throw new NotImplementedException(),
        };

    public static double GetProductionPerMinuteFactor(this ProductionBuildingEnum pt) =>
        pt switch
        {
            ProductionBuildingEnum.Monasterybrewery => 1.5,
            ProductionBuildingEnum.Printinghouse => 3.0,
            ProductionBuildingEnum.Bakery => 4.0,
            ProductionBuildingEnum.Silkweavingmill => 3.0,
            ProductionBuildingEnum.Redsmithsworkshop => 2.0,
            ProductionBuildingEnum.Carpetworkshop => 1.5,
            ProductionBuildingEnum.Ciderfarm => 1.5,
            ProductionBuildingEnum.Roastinghouse => 1.0,
            ProductionBuildingEnum.Dateplantation => 3.0,
            ProductionBuildingEnum.Fishermanshut => 2.0,
            ProductionBuildingEnum.Furriersworkshop => 2.5,
            ProductionBuildingEnum.Opticiansworkshop => 2.0,
            ProductionBuildingEnum.Tannery => 4.0,
            ProductionBuildingEnum.Weavershut => 2.0,
            ProductionBuildingEnum.Confectionersworkshop => 4.0,
            ProductionBuildingEnum.Butchersshop => 2.5,
            ProductionBuildingEnum.Goatfarm => 1.5,
            ProductionBuildingEnum.Pearlworkshop => 1.0,
            ProductionBuildingEnum.Perfumery => 1.0,
            ProductionBuildingEnum.Spicefarm => 2.0,
            ProductionBuildingEnum.Winepress => 2.0,
            _ => throw new NotImplementedException()
        };
}



// TODO replace this sometime
public enum Anno1404ProductType
{
    Beer,
    Books,
    Bread,
    BrocadeRobes,
    Candlestick,
    Carpets,
    Cider,
    Coffee,
    Dates,
    Fish,
    FurCoats,
    Glasses,
    LeatherJerkins,
    LinenGarments,
    Marzipan,
    Meat,
    Milk,
    PearlNecklaces,
    Perfume,
    Spices,
    Wine
}